import { existsSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import * as p from "@clack/prompts"
import { createCommand } from "commander"
import pc from "picocolors"
import { scanProject } from "./init-scanner.js"

export interface InitAnswers {
  projectName: string
  style: string
  domains: { name: string; path: string; canAccess?: string[]; cannotAccess?: string[] }[]
  autonomy: string
  frontend?: string
  backend?: string
  orm?: string
  enforceBoundaries: boolean
  driftDetection: boolean
  aiGovernance: boolean
}

export function generateConfigYml(answers: InitAnswers): string {
  const lines: string[] = [
    "# Structura Architecture Configuration",
    "# Generated by `structura init`",
    "",
    "project:",
    `  name: ${answers.projectName}`,
    "",
    "architecture:",
    `  style: ${answers.style}`,
    "",
  ]

  if (answers.frontend) {
    lines.push("frontend:")
    lines.push(`  framework: ${answers.frontend}`)
    lines.push("")
  }

  if (answers.backend) {
    lines.push("backend:")
    lines.push(`  framework: ${answers.backend}`)
    if (answers.orm) {
      lines.push(`  orm: ${answers.orm}`)
    }
    lines.push("")
  }

  lines.push("domains:")

  for (const domain of answers.domains) {
    lines.push(`  - name: ${domain.name}`)
    lines.push(`    path: ${domain.path}`)
    if (domain.canAccess && domain.canAccess.length > 0) {
      lines.push(`    canAccess: [${domain.canAccess.join(", ")}]`)
    }
    if (domain.cannotAccess && domain.cannotAccess.length > 0) {
      lines.push(`    cannotAccess: [${domain.cannotAccess.join(", ")}]`)
    }
  }

  lines.push("")

  if (answers.enforceBoundaries) {
    lines.push("rules:")
    lines.push("  forbid_cross_domain_imports: true")
    lines.push("")
  }

  lines.push("ai:")
  lines.push(`  autonomy: ${answers.autonomy}`)
  lines.push("")

  lines.push("features:")
  lines.push(`  drift_detection: ${answers.driftDetection}`)
  lines.push(`  ai_governance: ${answers.aiGovernance}`)
  lines.push("")

  return lines.join("\n")
}

async function askAllQuestions(
  s: ReturnType<typeof p.spinner>,
): Promise<InitAnswers> {
  const projectName = await p.text({
    message: "Project name:",
    placeholder: "my-app",
    defaultValue: "my-app",
  })
  if (p.isCancel(projectName)) return process.exit(0) as never

  const style = await p.select({
    message: "Architecture style:",
    options: [
      { value: "monolith", label: "Monolith", hint: "Single deployable unit" },
      {
        value: "modular-monolith",
        label: "Modular Monolith",
        hint: "Recommended — domains with boundaries",
      },
      {
        value: "microservices",
        label: "Microservices",
        hint: "Independent deployable services",
      },
    ],
  })
  if (p.isCancel(style)) return process.exit(0) as never

  const frontendVal = await p.select({
    message: "Frontend framework:",
    options: [
      { value: "", label: "None", hint: "No frontend" },
      { value: "nextjs", label: "Next.js" },
      { value: "react", label: "React (Vite)" },
    ],
  })
  if (p.isCancel(frontendVal)) return process.exit(0) as never

  const backendVal = await p.select({
    message: "Backend framework:",
    options: [
      { value: "", label: "None", hint: "No backend" },
      { value: "nestjs", label: "NestJS" },
      { value: "express", label: "Express" },
    ],
  })
  if (p.isCancel(backendVal)) return process.exit(0) as never

  let ormVal = ""
  if (backendVal) {
    const ormResult = await p.select({
      message: "ORM:",
      options: [
        { value: "", label: "None" },
        { value: "prisma", label: "Prisma" },
        { value: "drizzle", label: "Drizzle" },
        { value: "typeorm", label: "TypeORM" },
        { value: "sequelize", label: "Sequelize" },
      ],
    })
    if (p.isCancel(ormResult)) return process.exit(0) as never
    ormVal = ormResult as string
  }

  s.start("Scanning project structure")
  const scanResult = scanProject(process.cwd())
  s.stop(`Found ${scanResult.domains.length} domain(s)`)

  let domains: { name: string; path: string }[] = []

  if (scanResult.domains.length > 0) {
    console.log("")
    for (const d of scanResult.domains) {
      const icon = d.detected ? pc.green("✓") : pc.dim("○")
      console.log(`  ${icon} ${d.name} ${pc.dim(`(${d.path})`)}`)
    }
    console.log("")

    const accept = await p.confirm({
      message: "Accept these domains?",
      initialValue: true,
    })
    if (p.isCancel(accept)) return process.exit(0) as never

    if (accept) {
      domains = scanResult.domains.map((d) => ({
        name: d.name.includes("/") ? d.name.split("/").pop() ?? d.name : d.name.replace(/^@[^/]+\//, ""),
        path: d.path,
      }))
    }
  }

  if (domains.length === 0) {
    while (true) {
      const domainName = await p.text(
        domains.length === 0
          ? { message: "Domain name:", placeholder: "billing" }
          : { message: `Domain name (#${domains.length + 1}):` },
      )
      if (p.isCancel(domainName)) return process.exit(0) as never
      if (!domainName) {
        if (domains.length > 0) break
        continue
      }
      const domainPath = await p.text({
        message: `Path for "${domainName}":`,
        placeholder: `src/${domainName}`,
        defaultValue: `src/${domainName}`,
      })
      if (p.isCancel(domainPath)) return process.exit(0) as never
      domains.push({ name: domainName, path: domainPath })
      const more = await p.confirm({ message: "Add another domain?" })
      if (p.isCancel(more) || !more) break
    }
    if (domains.length === 0) domains.push({ name: "app", path: "src/app" })
  }

  const configureRules = await p.confirm({
    message: "Configure access rules between domains?",
    initialValue: domains.length > 1,
  })
  if (p.isCancel(configureRules)) return process.exit(0) as never

  if (configureRules) {
    for (let i = 0; i < domains.length; i++) {
      const domain = domains[i]!
      const others = domains.filter((_, idx) => idx !== i)
      if (others.length === 0) continue
      const cannotAccess = await p.multiselect({
        message: `Which domains should "${domain.name}" NOT access?`,
        options: others.map((d) => ({ value: d.name, label: d.name })),
        required: false,
      })
      if (p.isCancel(cannotAccess)) return process.exit(0) as never
      if (cannotAccess && cannotAccess.length > 0) {
        ;(domain as Record<string, unknown>).cannotAccess = cannotAccess
        ;(domain as Record<string, unknown>).canAccess = others
          .filter((d) => !(cannotAccess as string[]).includes(d.name))
          .map((d) => d.name)
      } else {
        ;(domain as Record<string, unknown>).canAccess = others.map((d) => d.name)
      }
    }
  }

  const enforceBoundaries = await p.confirm({
    message: "Enforce domain boundaries?",
    initialValue: true,
  })
  if (p.isCancel(enforceBoundaries)) return process.exit(0) as never

  const driftDetection = await p.confirm({
    message: "Enable drift detection?",
    initialValue: true,
  })
  if (p.isCancel(driftDetection)) return process.exit(0) as never

  const aiGovernance = await p.confirm({
    message: "Enable AI governance? (generate .md files for AI tools)",
    initialValue: true,
  })
  if (p.isCancel(aiGovernance)) return process.exit(0) as never

  const autonomy = await p.select({
    message: "AI agent autonomy level:",
    options: [
      { value: "constrained", label: "Constrained", hint: "Strict rules — recommended" },
      { value: "guided", label: "Guided", hint: "Can suggest but not violate" },
      { value: "supervised", label: "Supervised", hint: "Experimental — free but reports violations" },
    ],
  })
  if (p.isCancel(autonomy)) return process.exit(0) as never

  return {
    projectName: projectName as string,
    style: style as string,
    domains: domains as InitAnswers["domains"],
    autonomy: autonomy as string,
    frontend: (frontendVal as string) || undefined,
    backend: (backendVal as string) || undefined,
    orm: ormVal || undefined,
    enforceBoundaries: enforceBoundaries as boolean,
    driftDetection: driftDetection as boolean,
    aiGovernance: aiGovernance as boolean,
  }
}

export async function runInitFlow(options?: {
  force?: boolean
  manual?: boolean
  silent?: boolean
}): Promise<{ configPath: string } | null> {
  const configPath = join(process.cwd(), "structura.yml")

  if (existsSync(configPath) && !options?.force) {
    if (options?.silent) return null
    const overwrite = await p.confirm({
      message: "structura.yml already exists. Overwrite?",
    })
    if (p.isCancel(overwrite) || !overwrite) {
      p.outro("Init cancelled.")
      return null
    }
  }

  if (!options?.silent) {
    p.intro(pc.bold("structura init"))
  }

  const s = p.spinner()

  const answers = await askAllQuestions(s)

  s.start("Generating structura.yml")
  const content = generateConfigYml(answers)
  writeFileSync(configPath, content, "utf-8")
  s.stop("Config generated")

  if (!options?.silent) {
    p.note(content, "structura.yml")
  }

  return { configPath }
}

export const initCommand = createCommand("init")
  .description("Initialize Structura in your project")
  .option("-f, --force", "Overwrite existing structura.yml")
  .option("--manual", "Skip auto-scan and enter domains manually")
  .action(async (options: { force?: boolean; manual?: boolean }) => {
    const result = await runInitFlow({ force: options.force, manual: options.manual })
    if (!result) return

    p.outro(
      `${pc.green("✔")} Structura initialized!\n` +
        `  ${pc.cyan("structura check")}    Validate architecture\n` +
        `  ${pc.cyan("structura drift")}    Detect architecture drift\n` +
        `  ${pc.cyan("structura sync-ai")}  Sync AI adapters`,
    )
  })
