import { existsSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import * as p from "@clack/prompts"
import { createCommand } from "commander"
import pc from "picocolors"

function generateConfigYml(answers: {
  projectName: string
  style: string
  domains: { name: string; path: string }[]
  autonomy: string
  frontend?: string
  backend?: string
}): string {
  const lines: string[] = [
    "# Structura Architecture Configuration",
    "# Generated by `structura init`",
    "",
    "project:",
    `  name: ${answers.projectName}`,
    "",
    "architecture:",
    `  style: ${answers.style}`,
    "",
  ]

  if (answers.frontend) {
    lines.push("frontend:")
    lines.push(`  framework: ${answers.frontend}`)
    lines.push("")
  }

  if (answers.backend) {
    lines.push("backend:")
    lines.push(`  framework: ${answers.backend}`)
    lines.push("")
  }

  lines.push("domains:")

  for (const domain of answers.domains) {
    lines.push(`  - name: ${domain.name}`)
    lines.push(`    path: ${domain.path}`)
  }

  lines.push("")
  lines.push("ai:")
  lines.push(`  autonomy: ${answers.autonomy}`)
  lines.push("")

  return lines.join("\n")
}

export const initCommand = createCommand("init")
  .description("Initialize Structura in your project")
  .option("-f, --force", "Overwrite existing structura.yml")
  .action(async (options: { force?: boolean }) => {
    const configPath = join(process.cwd(), "structura.yml")

    if (existsSync(configPath) && !options.force) {
      const overwrite = await p.confirm({
        message: "structura.yml already exists. Overwrite?",
      })

      if (p.isCancel(overwrite) || !overwrite) {
        p.outro("Init cancelled.")
        return
      }
    }

    p.intro(pc.bold("structura init"))

    const projectName = await p.text({
      message: "What is your project name?",
      placeholder: "my-app",
      defaultValue: "my-app",
    })

    if (p.isCancel(projectName)) {
      p.outro("Init cancelled.")
      return
    }

    const style = await p.select({
      message: "Architecture style:",
      options: [
        { value: "monolith", label: "Monolith", hint: "Single deployable unit" },
        {
          value: "modular-monolith",
          label: "Modular Monolith",
          hint: "Recommended — domains with boundaries",
        },
        {
          value: "microservices",
          label: "Microservices",
          hint: "Independent deployable services",
        },
      ],
    })

    if (p.isCancel(style)) {
      p.outro("Init cancelled.")
      return
    }

    const frontend = await p.select({
      message: "Frontend framework:",
      options: [
        { value: "", label: "None", hint: "No frontend" },
        { value: "nextjs", label: "Next.js" },
        { value: "react", label: "React (Vite)" },
      ],
    })

    if (p.isCancel(frontend)) {
      p.outro("Init cancelled.")
      return
    }

    const backend = await p.select({
      message: "Backend framework:",
      options: [
        { value: "", label: "None", hint: "No backend" },
        { value: "nestjs", label: "NestJS" },
        { value: "express", label: "Express" },
      ],
    })

    if (p.isCancel(backend)) {
      p.outro("Init cancelled.")
      return
    }

    const domains: { name: string; path: string }[] = []

    while (true) {
      const domainName = await p.text(
        domains.length === 0
          ? { message: "Domain name:", placeholder: "billing" }
          : { message: `Domain name (#${domains.length + 1}):` },
      )

      if (p.isCancel(domainName)) {
        p.outro("Init cancelled.")
        return
      }

      if (!domainName) {
        if (domains.length > 0) break
        continue
      }

      const domainPath = await p.text({
        message: `Path for "${domainName}":`,
        placeholder: `src/${domainName}`,
        defaultValue: `src/${domainName}`,
      })

      if (p.isCancel(domainPath)) {
        p.outro("Init cancelled.")
        return
      }

      domains.push({ name: domainName, path: domainPath })

      const more = await p.confirm({
        message: "Add another domain?",
      })

      if (p.isCancel(more) || !more) break
    }

    if (domains.length === 0) {
      domains.push({ name: "app", path: "src/app" })
    }

    const autonomy = await p.select({
      message: "AI agent autonomy level:",
      options: [
        {
          value: "constrained",
          label: "Constrained",
          hint: "Strict rules — recommended",
        },
        {
          value: "guided",
          label: "Guided",
          hint: "Can suggest but not violate",
        },
        {
          value: "supervised",
          label: "Supervised",
          hint: "Experimental — free but reports violations",
        },
      ],
    })

    if (p.isCancel(autonomy)) {
      p.outro("Init cancelled.")
      return
    }

    const s = p.spinner()
    s.start("Generating structura.yml")

    const content = generateConfigYml({
      projectName: projectName as string,
      style: style as string,
      domains,
      autonomy: autonomy as string,
      frontend: (frontend as string) || undefined,
      backend: (backend as string) || undefined,
    })

    writeFileSync(configPath, content, "utf-8")
    s.stop("Config generated")

    p.note(content, "structura.yml")

    p.outro(
      `${pc.green("✔")} Structura initialized!\n` +
        `  ${pc.cyan("structura check")}    Validate architecture\n` +
        `  ${pc.cyan("structura drift")}    Detect architecture drift\n` +
        `  ${pc.cyan("structura sync-ai")}  Sync AI adapters`,
    )
  })
