import { createCommand } from "commander"
import * as p from "@clack/prompts"
import pc from "picocolors"
import { writeFileSync, existsSync, mkdirSync } from "node:fs"
import { join } from "node:path"
import { findConfigPath, readConfig } from "@structura/config"
import { generateIR } from "@structura/ir"
import type { ArchitectureIR } from "@structura/ir"

function generateCursorrules(ir: ArchitectureIR): string {
  const lines: string[] = []
  lines.push("# Structura Architecture Rules")
  lines.push("")
  lines.push("## Project")
  lines.push(`- Project: ${ir.meta.projectName}`)
  lines.push(`- Architecture Style: ${ir.meta.projectStyle}`)
  lines.push("")

  lines.push("## Domains")
  for (const domain of ir.domains) {
    const canAccess = domain.canAccess.length > 0
      ? domain.canAccess.join(", ")
      : "(none)"
    const cannotAccess = domain.cannotAccess.length > 0
      ? domain.cannotAccess.join(", ")
      : "(none)"
    lines.push(`### ${domain.name}`)
    lines.push(`- Path: \`${domain.path}\``)
    lines.push(`- Can access: ${canAccess}`)
    lines.push(`- Cannot access: ${cannotAccess}`)
    if (domain.naming) {
      if (domain.naming.files) lines.push(`- File naming: \`${domain.naming.files}\``)
      if (domain.naming.exports) lines.push(`- Export naming: \`${domain.naming.exports}\``)
    }
    lines.push("")
  }

  lines.push("## Dependencies")
  for (const dep of ir.dependencies) {
    const status = dep.allowed ? "allowed" : "forbidden"
    const reason = dep.reason ? ` (${dep.reason})` : ""
    lines.push(`- ${dep.sourceId} -> ${dep.targetId}: ${status}${reason}`)
  }
  lines.push("")

  const constrained = ir.aiPolicies.filter((p) => p.autonomy === "constrained")
  const guided = ir.aiPolicies.filter((p) => p.autonomy === "guided")

  if (constrained.length > 0) {
    lines.push("## Constrained Domains (AI cannot modify)")
    for (const p of constrained) {
      lines.push(`- ${p.domainId}`)
    }
    lines.push("")
  }

  if (guided.length > 0) {
    lines.push("## Guided Domains (AI must follow architecture)")
    for (const p of guided) {
      lines.push(`- ${p.domainId}`)
    }
    lines.push("")
  }

  return lines.join("\n")
}

function generateClaudeMd(ir: ArchitectureIR): string {
  const lines: string[] = []
  lines.push(`# ${ir.meta.projectName} — Architecture`)
  lines.push("")
  lines.push(`> Architecture style: **${ir.meta.projectStyle}**`)
  lines.push("")
  lines.push("## Domains")
  lines.push("")
  lines.push("| Domain | Path | Can Access | Cannot Access |")
  lines.push("|--------|------|------------|---------------|")
  for (const domain of ir.domains) {
    const can = domain.canAccess.join(", ") || "-"
    const cannot = domain.cannotAccess.join(", ") || "-"
    lines.push(`| ${domain.name} | \`${domain.path}\` | ${can} | ${cannot} |`)
  }
  lines.push("")
  lines.push("## Dependency Rules")
  lines.push("")
  for (const dep of ir.dependencies) {
    const icon = dep.allowed ? "✅" : "❌"
    const reason = dep.reason ? ` — ${dep.reason}` : ""
    lines.push(`- ${icon} **${dep.sourceId}** → **${dep.targetId}** (${dep.allowed ? "allowed" : "forbidden"})${reason}`)
  }
  lines.push("")
  lines.push("## AI Governance")
  lines.push("")
  if (ir.aiPolicies.length > 0) {
    lines.push("| Domain | Autonomy |")
    lines.push("|--------|----------|")
    for (const p of ir.aiPolicies) {
      const labels = { constrained: "🔒 Constrained", guided: "🧭 Guided", supervised: "👁 Supervised" }
      lines.push(`| ${p.domainId} | ${labels[p.autonomy] ?? p.autonomy} |`)
    }
  } else {
    lines.push("No AI policies defined.")
  }
  lines.push("")
  lines.push("---")
  lines.push("*This file is auto-generated by \`structura sync-ai\`. Do not edit manually.*")
  return lines.join("\n")
}

function generateCopilotInstructions(ir: ArchitectureIR): string {
  const lines: string[] = []
  lines.push("# Architecture Context for GitHub Copilot")
  lines.push("")
  lines.push(`Project: ${ir.meta.projectName}`)
  lines.push(`Architecture: ${ir.meta.projectStyle}`)
  lines.push("")
  lines.push("## Domain Boundaries")
  for (const domain of ir.domains) {
    lines.push(`- **${domain.name}** (\`${domain.path}\`)`)
    if (domain.cannotAccess.length > 0) {
      lines.push(`  - Do NOT import from: ${domain.cannotAccess.join(", ")}`)
    }
    if (domain.canAccess.length > 0) {
      lines.push(`  - May import from: ${domain.canAccess.join(", ")}`)
    }
  }
  lines.push("")
  lines.push("## Restricted Dependencies")
  for (const dep of ir.dependencies) {
    if (!dep.allowed) {
      lines.push(`- Do NOT create imports from **${dep.sourceId}** to **${dep.targetId}**`)
    }
  }
  return lines.join("\n")
}

export const syncAiCommand = createCommand("sync-ai")
  .description("Generate AI governance files (.cursorrules, CLAUDE.md, copilot-instructions.md)")
  .option("--dry-run", "Show generated content without writing files")
  .option("--force", "Overwrite existing files")
  .action(async (options: { dryRun?: boolean; force?: boolean }) => {
    p.intro(pc.bold("structura sync-ai"))

    const s = p.spinner()

    s.start("Finding configuration")
    const configPath = findConfigPath(process.cwd())
    if (!configPath) {
      s.stop("Config not found")
      p.outro(`${pc.red("✖")} No structura.yml found.`)
      process.exit(1)
    }
    s.stop(`Found ${pc.cyan(configPath)}`)

    s.start("Reading config and generating IR")
    const configResult = readConfig(configPath)
    if (!configResult.ok) {
      s.stop("Config validation failed")
      p.outro(`${pc.red("✖")} ${configResult.error.message}`)
      process.exit(1)
    }
    s.stop("Config loaded")

    const config = configResult.value
    const ir = generateIR(config)

    const root = process.cwd()
    const files: { path: string; content: string; label: string }[] = [
      {
        path: join(root, ".cursorrules"),
        content: generateCursorrules(ir),
        label: ".cursorrules",
      },
      {
        path: join(root, "CLAUDE.md"),
        content: generateClaudeMd(ir),
        label: "CLAUDE.md",
      },
      {
        path: join(root, ".github", "copilot-instructions.md"),
        content: generateCopilotInstructions(ir),
        label: ".github/copilot-instructions.md",
      },
    ]

    if (options.dryRun) {
      s.stop("Dry-run mode")
      for (const file of files) {
        console.log(`\n${pc.bold(`=== ${file.label} ===`)}`)
        console.log(file.content)
      }
      p.outro(pc.yellow("⚠") + " Dry-run complete — no files written")
      return
    }

    let written = 0
    let skipped = 0

    for (const file of files) {
      if (existsSync(file.path) && !options.force) {
        p.log.warn(`${pc.dim(file.label)} already exists (use --force to overwrite)`)
        skipped++
        continue
      }

      const dir = file.path.includes("\\") ? file.path.substring(0, file.path.lastIndexOf("\\"))
        : file.path.includes("/") ? file.path.substring(0, file.path.lastIndexOf("/"))
        : ""
      if (dir && !existsSync(dir)) {
        mkdirSync(dir, { recursive: true })
      }

      writeFileSync(file.path, file.content, "utf-8")
      written++
    }

    s.stop(`Generated ${written} file(s)` + (skipped > 0 ? ` (${skipped} skipped)` : ""))

    if (written > 0) {
      console.log(`\n${pc.bold("Generated files:")}`)
      for (const file of files) {
        const exists = existsSync(file.path)
        console.log(`  ${exists ? pc.green("✓") : pc.dim("—")} ${file.label}`)
      }
    }

    p.outro(pc.green("✔") + " AI sync complete")
  })
