import { createCommand } from "commander"
import * as p from "@clack/prompts"
import pc from "picocolors"
import { writeFileSync, existsSync, mkdirSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { generateIR } from "@structura/ir"
import type { ArchitectureIR } from "@structura/ir"
import { ensureConfig } from "../utils/config.js"

const STRUCTURA_MARKER_START = "<!-- STRUCTURA:ARCHITECTURE -->"
const STRUCTURA_MARKER_END = "<!-- /STRUCTURA:ARCHITECTURE -->"

interface Generator {
  id: string
  label: string
  filePath: (root: string) => string
  generate: (ir: ArchitectureIR) => string
  merge?: (existing: string, generated: string) => string
}

function generateCursorrules(ir: ArchitectureIR): string {
  const lines: string[] = []
  lines.push("# Structura Architecture Rules")
  lines.push("")
  lines.push(`## ${ir.meta.projectName}`)
  lines.push(`- Architecture Style: ${ir.meta.projectStyle}`)
  lines.push("")

  lines.push("## Domains")
  for (const domain of ir.domains) {
    const canAccess = domain.canAccess.length > 0
      ? domain.canAccess.join(", ")
      : "(none)"
    const cannotAccess = domain.cannotAccess.length > 0
      ? domain.cannotAccess.join(", ")
      : "(none)"
    lines.push(`### ${domain.name}`)
    lines.push(`- Path: \`${domain.path}\``)
    lines.push(`- Can access: ${canAccess}`)
    lines.push(`- Cannot access: ${cannotAccess}`)
    if (domain.naming?.files) lines.push(`- File naming: \`${domain.naming.files}\``)
    if (domain.naming?.exports) lines.push(`- Export naming: \`${domain.naming.exports}\``)
    lines.push("")
  }

  lines.push("## Dependencies")
  for (const dep of ir.dependencies) {
    const status = dep.allowed ? "allowed" : "forbidden"
    const reason = dep.reason ? ` (${dep.reason})` : ""
    lines.push(`- ${dep.sourceId} -> ${dep.targetId}: ${status}${reason}`)
  }
  lines.push("")

  for (const autonomy of ["constrained", "guided"] as const) {
    const domains = ir.aiPolicies.filter((p) => p.autonomy === autonomy)
    if (domains.length > 0) {
      const label = autonomy === "constrained"
        ? "Constrained Domains (AI cannot modify)"
        : "Guided Domains (AI must follow architecture)"
      lines.push(`## ${label}`)
      for (const p of domains) {
        lines.push(`- ${p.domainId}`)
      }
      lines.push("")
    }
  }

  return lines.join("\n")
}

function generateClaudeMd(ir: ArchitectureIR): string {
  const lines: string[] = []
  lines.push(`# ${ir.meta.projectName} — Architecture`)
  lines.push("")
  lines.push(`> Architecture style: **${ir.meta.projectStyle}**`)
  lines.push("")
  lines.push("## Domains")
  lines.push("")
  lines.push("| Domain | Path | Can Access | Cannot Access |")
  lines.push("|--------|------|------------|---------------|")
  for (const domain of ir.domains) {
    const can = domain.canAccess.join(", ") || "-"
    const cannot = domain.cannotAccess.join(", ") || "-"
    lines.push(`| ${domain.name} | \`${domain.path}\` | ${can} | ${cannot} |`)
  }
  lines.push("")
  lines.push("## Dependency Rules")
  lines.push("")
  for (const dep of ir.dependencies) {
    const icon = dep.allowed ? "✅" : "❌"
    const reason = dep.reason ? ` — ${dep.reason}` : ""
    lines.push(`- ${icon} **${dep.sourceId}** → **${dep.targetId}** (${dep.allowed ? "allowed" : "forbidden"})${reason}`)
  }
  lines.push("")
  lines.push("## AI Governance")
  lines.push("")
  if (ir.aiPolicies.length > 0) {
    lines.push("| Domain | Autonomy |")
    lines.push("|--------|----------|")
    for (const p of ir.aiPolicies) {
      const labels = { constrained: "🔒 Constrained", guided: "🧭 Guided", supervised: "👁 Supervised" }
      lines.push(`| ${p.domainId} | ${labels[p.autonomy] ?? p.autonomy} |`)
    }
  } else {
    lines.push("No AI policies defined.")
  }
  lines.push("")
  lines.push("---")
  lines.push("*This file is auto-generated by `structura sync-ai`. Do not edit manually.*")
  return lines.join("\n")
}

function generateCopilotInstructions(ir: ArchitectureIR): string {
  const lines: string[] = []
  lines.push("# Architecture Context for GitHub Copilot")
  lines.push("")
  lines.push(`Project: ${ir.meta.projectName}`)
  lines.push(`Architecture: ${ir.meta.projectStyle}`)
  lines.push("")
  lines.push("## Domain Boundaries")
  for (const domain of ir.domains) {
    lines.push(`- **${domain.name}** (\`${domain.path}\`)`)
    if (domain.cannotAccess.length > 0) {
      lines.push(`  - Do NOT import from: ${domain.cannotAccess.join(", ")}`)
    }
    if (domain.canAccess.length > 0) {
      lines.push(`  - May import from: ${domain.canAccess.join(", ")}`)
    }
  }
  lines.push("")
  lines.push("## Restricted Dependencies")
  for (const dep of ir.dependencies) {
    if (!dep.allowed) {
      lines.push(`- Do NOT create imports from **${dep.sourceId}** to **${dep.targetId}**`)
    }
  }
  return lines.join("\n")
}

function generateOpenCode(ir: ArchitectureIR): string {
  const lines: string[] = []
  lines.push("## Arquitetura do Projeto")
  lines.push("")
  lines.push(`Estilo: **${ir.meta.projectStyle}**`)
  lines.push("")
  lines.push("### Dominios")
  lines.push("")
  lines.push("| Dominio | Caminho | Pode Acessar | Nao Pode Acessar |")
  lines.push("|---------|---------|--------------|------------------|")
  for (const domain of ir.domains) {
    const can = domain.canAccess.join(", ") || "-"
    const cannot = domain.cannotAccess.join(", ") || "-"
    lines.push(`| ${domain.name} | \`${domain.path}\` | ${can} | ${cannot} |`)
  }
  lines.push("")
  lines.push("### Dependencias")
  lines.push("")
  for (const dep of ir.dependencies) {
    const icon = dep.allowed ? "✅ permitido" : "❌ proibido"
    const reason = dep.reason ? ` — ${dep.reason}` : ""
    lines.push(`- ${icon}: **${dep.sourceId}** → **${dep.targetId}**${reason}`)
  }
  lines.push("")
  lines.push("### Politicas de IA")
  lines.push("")
  if (ir.aiPolicies.length > 0) {
    lines.push("| Dominio | Autonomia |")
    lines.push("|---------|-----------|")
    for (const p of ir.aiPolicies) {
      const labels = { constrained: "🔒 Restrito", guided: "🧭 Guiado", supervised: "👁 Supervisionado" }
      lines.push(`| ${p.domainId} | ${labels[p.autonomy] ?? p.autonomy} |`)
    }
  } else {
    lines.push("Nenhuma politica definida.")
  }
  return lines.join("\n")
}

function mergeIntoAgentsMd(existing: string, generated: string): string {
  const startIdx = existing.indexOf(STRUCTURA_MARKER_START)
  const endIdx = existing.indexOf(STRUCTURA_MARKER_END)

  const block = [
    "",
    STRUCTURA_MARKER_START,
    generated,
    STRUCTURA_MARKER_END,
    "",
  ].join("\n")

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = existing.slice(0, startIdx).replace(/\n*$/, "")
    const after = existing.slice(endIdx + STRUCTURA_MARKER_END.length)
    return before + block + after
  }

  return existing.replace(/\n*$/, "") + block
}

function generateWindsurfRules(ir: ArchitectureIR): string {
  const lines: string[] = []
  lines.push("# Windsurf AI Rules — Structura Architecture")
  lines.push("")
  lines.push(`Project: ${ir.meta.projectName}`)
  lines.push(`Architecture: ${ir.meta.projectStyle}`)
  lines.push("")
  lines.push("## Rules")
  for (const dep of ir.dependencies) {
    if (!dep.allowed) {
      lines.push(`- NEVER import from ${dep.sourceId} into ${dep.targetId}`)
    }
  }
  for (const domain of ir.domains) {
    for (const forbidden of domain.cannotAccess) {
      lines.push(`- NEVER import from ${forbidden} inside ${domain.name}`)
    }
  }
  lines.push("")
  lines.push("## Constrained Domains")
  for (const p of ir.aiPolicies) {
    if (p.autonomy === "constrained") {
      lines.push(`- ${p.domainId}: AI must NOT modify code in this domain`)
    }
  }
  return lines.join("\n")
}

function generateContinueRc(ir: ArchitectureIR): string {
  const rules = []
  for (const dep of ir.dependencies) {
    if (!dep.allowed) {
      rules.push({
        id: `no-import-${dep.sourceId}-${dep.targetId}`,
        description: `Do not import from ${dep.sourceId} into ${dep.targetId}`,
      })
    }
  }
  for (const domain of ir.domains) {
    for (const forbidden of domain.cannotAccess) {
      rules.push({
        id: `no-access-${domain.name}-${forbidden}`,
        description: `${domain.name} must not access ${forbidden}`,
      })
    }
  }

  const obj: Record<string, unknown> = {
    name: ir.meta.projectName,
    description: `Architecture: ${ir.meta.projectStyle}`,
    rules,
    tabAutocompleteModel: {
      title: ir.meta.projectName,
    },
  }

  return JSON.stringify(obj, null, 2)
}

function generateAiderConventions(ir: ArchitectureIR): string {
  const lines: string[] = []
  lines.push("# Project Conventions")
  lines.push("")
  lines.push(`Architecture style: ${ir.meta.projectStyle}`)
  lines.push("")
  lines.push("## Domain structure")
  for (const domain of ir.domains) {
    lines.push(`- ${domain.name}: ${domain.path}`)
  }
  lines.push("")
  lines.push("## Import restrictions")
  for (const dep of ir.dependencies) {
    if (!dep.allowed) {
      lines.push(`- Do not create imports from ${dep.sourceId} to ${dep.targetId}`)
    }
  }
  return lines.join("\n")
}

const generators: Generator[] = [
  {
    id: "cursor",
    label: ".cursorrules",
    filePath: (root) => join(root, ".cursorrules"),
    generate: generateCursorrules,
  },
  {
    id: "claude",
    label: "CLAUDE.md",
    filePath: (root) => join(root, "CLAUDE.md"),
    generate: generateClaudeMd,
  },
  {
    id: "copilot",
    label: ".github/copilot-instructions.md",
    filePath: (root) => join(root, ".github", "copilot-instructions.md"),
    generate: generateCopilotInstructions,
  },
  {
    id: "opencode",
    label: "AGENTS.md",
    filePath: (root) => join(root, "AGENTS.md"),
    generate: generateOpenCode,
    merge: mergeIntoAgentsMd,
  },
  {
    id: "windsurf",
    label: ".windsurfrules",
    filePath: (root) => join(root, ".windsurfrules"),
    generate: generateWindsurfRules,
  },
  {
    id: "continue",
    label: ".continuerc",
    filePath: (root) => join(root, ".continuerc"),
    generate: generateContinueRc,
  },
  {
    id: "aider",
    label: "CONVENTIONS.md",
    filePath: (root) => join(root, "CONVENTIONS.md"),
    generate: generateAiderConventions,
  },
]

export const syncAiCommand = createCommand("sync-ai")
  .description("Generate AI context files for multiple AI coding tools")
  .option("--cursor", "Generate .cursorrules (Cursor IDE)")
  .option("--claude", "Generate CLAUDE.md (Claude Code)")
  .option("--copilot", "Generate .github/copilot-instructions.md (GitHub Copilot)")
  .option("--opencode", "Generate/update AGENTS.md (OpenCode)")
  .option("--windsurf", "Generate .windsurfrules (Windsurf)")
  .option("--continue", "Generate .continuerc (Continue.dev)")
  .option("--aider", "Generate CONVENTIONS.md (Aider)")
  .option("--all", "Generate all targets (default)")
  .option("--dry-run", "Show generated content without writing files")
  .option("--force", "Overwrite existing files")
  .option("--auto", "Auto-generate config if missing (non-interactive)")
  .action(async (options: {
    cursor?: boolean; claude?: boolean; copilot?: boolean;
    opencode?: boolean; windsurf?: boolean; continue?: boolean;
    aider?: boolean; all?: boolean;
    dryRun?: boolean; force?: boolean; auto?: boolean;
  }) => {
    p.intro(pc.bold("structura sync-ai"))
    const s = p.spinner()

    s.start("Finding configuration")
    const { config } = await ensureConfig({ auto: options.auto })
    s.stop("Config loaded")

    const ir = generateIR(config)

    const explicitFlags = [
      options.cursor, options.claude, options.copilot,
      options.opencode, options.windsurf, options.continue,
      options.aider,
    ]
    const hasExplicitTarget = explicitFlags.some(Boolean)
    const all = options.all ?? !hasExplicitTarget

    const selected = generators.filter((g) => {
      if (all) return true
      return options[g.id as keyof typeof options] === true
    })

    if (selected.length === 0) {
      p.outro(`${pc.yellow("⚠")} No targets selected. Use --all or a specific flag.`)
      return
    }

    const root = process.cwd()
    const results: { label: string; status: "written" | "skipped" | "dry-run" }[] = []

    if (options.dryRun) {
      s.stop("Dry-run mode")
      for (const gen of selected) {
        const content = gen.generate(ir)
        console.log(`\n${pc.bold(`=== ${gen.label} ===`)}`)
        console.log(content)
        results.push({ label: gen.label, status: "dry-run" })
      }
      const labels = results.map((r) => `  ${pc.dim("~")} ${r.label}`).join("\n")
      console.log(`\n${pc.bold("Would generate:")}\n${labels}`)
      p.outro(pc.yellow("⚠") + " Dry-run complete — no files written")
      return
    }

    for (const gen of selected) {
      const path = gen.filePath(root)
      const dir = path.includes("\\") ? path.substring(0, path.lastIndexOf("\\"))
        : path.includes("/") ? path.substring(0, path.lastIndexOf("/"))
        : ""

      const fileExists = existsSync(path)

      if (fileExists && !options.force) {
        if (gen.merge && gen.id === "opencode") {
          const existing = readFileSync(path, "utf-8")
          const generated = gen.generate(ir)
          const merged = gen.merge(existing, generated)
          writeFileSync(path, merged, "utf-8")
          results.push({ label: gen.label, status: "written" })
          continue
        }
        p.log.warn(`${pc.dim(gen.label)} already exists (use --force to overwrite)`)
        results.push({ label: gen.label, status: "skipped" })
        continue
      }

      if (dir && !existsSync(dir)) {
        mkdirSync(dir, { recursive: true })
      }

      let content: string
      if (fileExists && gen.merge) {
        const existing = readFileSync(path, "utf-8")
        content = gen.merge(existing, gen.generate(ir))
      } else if (gen.merge) {
        content = gen.merge("", gen.generate(ir))
      } else {
        content = gen.generate(ir)
      }

      writeFileSync(path, content, "utf-8")
      results.push({ label: gen.label, status: "written" })
    }

    const written = results.filter((r) => r.status === "written").length
    const skipped = results.filter((r) => r.status === "skipped").length

    s.stop(`Generated ${written} file(s)` + (skipped > 0 ? ` (${skipped} skipped)` : ""))

    console.log(`\n${pc.bold("Results:")}`)
    for (const r of results) {
      const icon = r.status === "written" ? pc.green("✓") : r.status === "skipped" ? pc.dim("—") : pc.dim("~")
      console.log(`  ${icon} ${r.label}`)
    }

    p.outro(pc.green("✔") + " AI sync complete")
  })
