import * as p from "@clack/prompts"
import pc from "picocolors"
import { writeFileSync, readFileSync } from "node:fs"
import { join } from "node:path"
import { findConfigPath, readConfig } from "@structura/config"
import type { StructuraConfig } from "@structura/config"
import { scanProject, type CandidateDomain } from "../commands/init-scanner.js"

function generateConfigYml(answers: {
  projectName: string
  style: string
  domains: { name: string; path: string; canAccess?: string[]; cannotAccess?: string[] }[]
  autonomy: string
}): string {
  const lines: string[] = [
    "# Structura Architecture Configuration",
    "# Generated by `structura init`",
    "",
    "project:",
    `  name: ${answers.projectName}`,
    "",
    "architecture:",
    `  style: ${answers.style}`,
    "",
  ]

  lines.push("domains:")
  for (const domain of answers.domains) {
    lines.push(`  - name: ${domain.name}`)
    lines.push(`    path: ${domain.path}`)
    if (domain.canAccess && domain.canAccess.length > 0) {
      lines.push(`    canAccess: [${domain.canAccess.join(", ")}]`)
    }
    if (domain.cannotAccess && domain.cannotAccess.length > 0) {
      lines.push(`    cannotAccess: [${domain.cannotAccess.join(", ")}]`)
    }
  }

  lines.push("")
  lines.push("ai:")
  lines.push(`  autonomy: ${answers.autonomy}`)
  lines.push("")

  return lines.join("\n")
}

function pickName(domain: CandidateDomain, rootPkgName: string): string {
  const base = domain.name
  if (base === rootPkgName) return base
  const scoped = base.includes("/") ? base.split("/").pop() ?? base : base
  return scoped
}

export async function ensureConfig(options?: { auto?: boolean }): Promise<{
  config: StructuraConfig
  configPath: string
}> {
  const root = process.cwd()
  const existingPath = findConfigPath(root)

  if (existingPath) {
    const result = readConfig(existingPath)
    if (!result.ok) {
      p.outro(`${pc.red("✖")} ${result.error.message}`)
      process.exit(1)
    }
    return { config: result.value, configPath: existingPath }
  }

  const s = p.spinner()
  s.start("Scanning project structure")
  const scanResult = scanProject(root)
  s.stop(`Found ${scanResult.domains.length} domain(s)`)

  console.log("")
  for (const d of scanResult.domains) {
    const icon = d.detected ? pc.green("✓") : pc.dim("○")
    console.log(`  ${icon} ${d.name} ${pc.dim(`(${d.path})`)}`)
  }
  console.log("")

  let accepted = true
  if (!options?.auto) {
    const response = await p.confirm({
      message: "Create structura.yml with these domains?",
      initialValue: true,
    })
    if (p.isCancel(response)) {
      p.outro("Aborted.")
      process.exit(1)
    }
    accepted = response
  }

  if (!accepted) {
    p.outro(`${pc.red("✖")} Config required. Run ${pc.cyan("structura init")} manually.`)
    process.exit(1)
  }

  let rootPkgName = "my-app"
  try {
    const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf-8"))
    rootPkgName = pkg.name ?? rootPkgName
  } catch {}

  const domains = scanResult.domains.map((d) => ({
    name: pickName(d, rootPkgName),
    path: d.path,
  }))

  s.start("Generating structura.yml")
  const content = generateConfigYml({
    projectName: rootPkgName,
    style: "modular-monolith",
    domains,
    autonomy: "constrained",
  })

  const configPath = join(root, "structura.yml")
  writeFileSync(configPath, content, "utf-8")
  s.stop(`Created ${pc.cyan("structura.yml")}`)

  const result = readConfig(configPath)
  if (!result.ok) {
    p.outro(`${pc.red("✖")} ${result.error.message}`)
    process.exit(1)
  }

  return { config: result.value, configPath }
}
